apiVersion: v1
kind: Pod
metadata:
  name: attacker
  namespace: vuln-psa-ns
spec:
  hostIPC: true
  containers:
  - name: attacker
    image: ubuntu
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "sleep 99999" ]
  nodeName: worker
