apiVersion: v1
kind: ConfigMap
metadata:
  name: db-simulation-script
  namespace: cnpg
data:
  simulate.py: |
    import psycopg2
    import random
    import time

    conn = psycopg2.connect(
        dbname="app",
        user="app",
        password="app",
        host="pooler-example-rw",
        port="5432"
    )
    cur = conn.cursor()

    cur.execute("""
    CREATE TABLE IF NOT EXISTS test_table (
        id SERIAL PRIMARY KEY,
        data INTEGER NOT NULL
    );
    """)
    conn.commit()

    operations = ["insert", "update", "delete", "select"]

    for _ in range(1000000):
        operation = random.choice(operations)
        if operation == "insert":
            cur.execute("INSERT INTO test_table (data) VALUES (%s)", (random.randint(1, 100),))
        elif operation == "update":
            cur.execute("UPDATE test_table SET data = %s WHERE id = %s", (random.randint(1, 100), random.randint(1, 10)))
        elif operation == "delete":
            cur.execute("DELETE FROM test_table WHERE id = %s", (random.randint(1, 10),))
        elif operation == "select":
            cur.execute("SELECT * FROM test_table LIMIT 1")
            print(cur.fetchone())

        conn.commit()
        #time.sleep(0.1)

    cur.close()
    conn.close()