apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: anime
  name: anime-depl
spec:
  replicas: 2
  selector:
    matchLabels:
      app: anime-app
  template:
    metadata:
      labels:
        app: anime-app
    spec:
      containers:
      - name: anime-cont
        image: truebad0ur/anime-webpage:v4
        ports:
        - containerPort: 80
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  namespace: anime
  name: anime-svc
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: anime-app
