apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: external-metrics
  namespace: monitoring
  labels:
    release: my-kube-prometheus-stack
spec:
  metricsPath: /metrics
  scheme: HTTPS
  staticConfigs:
    - targets:
        - "domain.local"
  basicAuth:
    username:
      name: external-metrics-secret
      key: username
    password:
      name: external-metrics-secret
      key: password

