apiVersion: v1
kind: Pod
metadata:
  name: writer-1
spec:
  containers:
  - name: writer
    image: busybox
    command: ["/bin/sh", "-c", "while true; do echo $(date) >> /mnt/shared/log.txt; sleep 5; done"]
    volumeMounts:
    - name: shared-volume
      mountPath: /mnt/shared
  volumes:
  - name: shared-volume
    persistentVolumeClaim:
      claimName: shared-rwx-pvc
---
apiVersion: v1
kind: Pod
metadata:
  name: writer-2
spec:
  containers:
  - name: writer
    image: busybox
    command: ["/bin/sh", "-c", "while true; do echo Appended data at $(date) >> /mnt/shared/log.txt; sleep 7; done"]
    volumeMounts:
    - name: shared-volume
      mountPath: /mnt/shared
  volumes:
  - name: shared-volume
    persistentVolumeClaim:
      claimName: shared-rwx-pvc
---
apiVersion: v1
kind: Pod
metadata:
  name: reader
spec:
  containers:
  - name: reader
    image: busybox
    command: ["/bin/sh", "-c", "while true; do cat /mnt/shared/log.txt; sleep 10; done"]
    volumeMounts:
    - name: shared-volume
      mountPath: /mnt/shared
  volumes:
  - name: shared-volume
    persistentVolumeClaim:
      claimName: shared-rwx-pvc
