apiVersion: v1
kind: ConfigMap
metadata:
  name: blackbox-exporter-config
  namespace: monitoring
data:
  blackbox.yml: |
    modules:
      http_2xx:
        prober: http
        timeout: 10s
        http:
          valid_http_versions: [ "HTTP/2.0" ]
          valid_status_codes: []
          method: GET
          preferred_ip_protocol: "ip4"
          headers:
            User-Agent: "Blackbox Exporter"
