apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: website-monitoring
  namespace: monitoring
  labels:
    release: my-kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: blackbox-exporter
  endpoints:
  - port: http
    path: /probe
    interval: 30s
    params:
      module: [http_2xx]
      target: ["kubehomelab.space"]
    relabelings:
    - sourceLabels: [__param_target]
      targetLabel: instance
  namespaceSelector:
    matchNames:
      - monitoring
