apiVersion: v1
kind: Pod
metadata:
  name: pod
  namespace: test
spec:
  containers:
  - name: container
    image: nginx:1.14.2
    ports:
    - containerPort: 80
    volumeMounts:
    - mountPath: "/usr/share/nginx/html"
      name: volume
    command: ["/bin/sh", "-c"]
    args:
    - echo '<html><h1>Welcome to Nginx!</h1></html>' > /usr/share/nginx/html/index.html && nginx -g 'daemon off;'
  volumes:
  - name: volume
    persistentVolumeClaim:
      claimName: pvc