apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc
  namespace: test
  finalizers:
    - kubernetes.io/pvc-protection
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn-rwx