apiVersion: v1
kind: Service
metadata:
  name: irc
  namespace: {{ .Values.namespaceOverride }}
spec:
  selector:
    app: thelounge
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
