apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
 name: letsencrypt
 namespace: cert-manager
spec:
 acme:
   email: pieceofcakecupofcoffee@gmail.com
   server: https://acme-v02.api.letsencrypt.org/directory
   privateKeySecretRef:
     name: issuer-account-key
   solvers:
     - http01:
         ingress:
           class: traefik
