apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana-cert
  namespace: monitoring
spec:
  commonName: grafana.kubehomelab.space
  secretName: grafana-cert
  dnsNames:
    - grafana.kubehomelab.space
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
