apiVersion: 1
groups:
    - orgId: 1
      name: 1min
      folder: alerts
      interval: 1m
      rules:
        - uid: edu0az2wx4qgwc
          title: CPU Temperature
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 3600
                to: 0
              datasourceUid: edtljryxa6i9sa
              model:
                datasource:
                    type: prometheus
                    uid: edtljryxa6i9sa
                expr: node_hwmon_temp_celsius
                interval: ""
                intervalMs: 15000
                legendFormat: '{{ node }} - {{ sensor }}'
                maxDataPoints: 43200
                refId: A
            - refId: B
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params: []
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - B
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                reducer: last
                refId: B
                type: reduce
            - refId: C
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 57.5
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: B
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          dashboardUid: fdtlkmr4pyd4we
          panelId: 5
          noDataState: NoData
          execErrState: Error
          for: 0s
          annotations:
            __dashboardUid__: fdtlkmr4pyd4we
            __panelId__: "5"
            description: ""
            runbook_url: ""
            summary: ""
          labels:
            "": ""
          isPaused: false
          notification_settings:
            receiver: Alert Bot
