apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: virtualtabletop
  name: virtualtabletop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: virtualtabletop
  template:
    metadata:
      labels:
        app: virtualtabletop
    spec:
      containers:
      - name: virtualtabletop
        image: truebad0ur/virtualtabletop:v2
        ports:
        - containerPort: 8272
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  namespace: virtualtabletop
  name: virtualtabletop
spec:
  ports:
  - port: 80
    targetPort: 8272
    protocol: TCP
    name: http
  selector:
    app: virtualtabletop
