apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: coffee
  namespace: web
spec:
  parentRefs:
  - name: https
    namespace: kgateway-system
    sectionName: https
  hostnames:
  - "cafe.kubehomelab.space"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /coffee
    backendRefs:
    - name: coffee
      namespace: web
      port: 80

---

apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: tea
  namespace: web
spec:
  parentRefs:
  - name: https
    namespace: kgateway-system
    sectionName: https
  hostnames:
  - "cafe.kubehomelab.space"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /tea
    backendRefs:
    - name: tea
      namespace: web
      port: 80
