apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: https
  namespace: kgateway-system
spec:
  secretName: https
  dnsNames:
    - cafe.kubehomelab.space
  issuerRef:
    name: letsencrypt-gateway
    kind: ClusterIssuer
