apiVersion: v1
kind: Pod
metadata:
  name: victim
spec:
  containers:
  - name: victim
    image: ubuntu
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "FLAG=supersecret sleep 9999999" ]
  nodeName: worker
