apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: multiarch-demo
  labels:
    app: multiarch-demo
spec:
  selector:
    matchLabels:
      app: multiarch-demo
  template:
    metadata:
      labels:
        app: multiarch-demo
    spec:
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
      containers:
        - name: multiarch-demo
          image: truebad0ur/multiarch-demo:latest
          ports:
            - containerPort: 80
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          resources:
            requests:
              cpu: 10m
              memory: 16Mi
            limits:
              cpu: 100m
              memory: 32Mi
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: multiarch-demo
  labels:
    app: multiarch-demo
spec:
  selector:
    app: multiarch-demo
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
