apiVersion: v1
kind: Service
metadata:
  name: tracee-svc
  namespace: tracee
spec:
  ports:
  - port: 80
    targetPort: 3366
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/instance: my-tracee
