apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test2-ingress
  annotations:
    traefik.ingress.kubernetes.io/router.tls: "false"
    kubernetes.io/ingress.class: "traefik"
    cert-manager.io/cluster-issuer: "letsencrypt"
spec:
  ingressClassName: "traefik"
  tls:
  - hosts:
    - x2.kubehomelab.space
    secretName: root-domain-tls-2
  rules:
  - host: x2.kubehomelab.space
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: test2-svc
            port:
              number: 80
