apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: anime-ingress
  namespace: anime
  annotations:
    traefik.ingress.kubernetes.io/router.tls: "true"
    kubernetes.io/ingress.class: "traefik"
    cert-manager.io/cluster-issuer: "letsencrypt"
spec:
  ingressClassName: "traefik"
  tls:
  - hosts:
    - kubehomelab.space
    secretName: anime-cert
  rules:
  - host: kubehomelab.space
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: anime-svc
            port:
              number: 80
