apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-traefik-http
  namespace: anime
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
    traefik.ingress.kubernetes.io/router.middlewares: traefik-redirect-to-https@kubernetescrd
    kubernetes.io/ingress.class: traefik
spec:
  ingressClassName: "traefik"
  rules:
    - host: anime.kubehomelab.space
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: anime-svc
                port:
                  number: 80
