apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argo-cd
spec:
  project: default
  sources:
    - repoURL: https://grafana.github.io/helm-charts
      chart: loki
      targetRevision: 7.3.0
      helm:
        releaseName: loki
        valueFiles:
          - $values/configs/loki/values.yml
    - repoURL: https://github.com/TrueBad0ur/local-raspberry-kube-cluster.git
      targetRevision: main
      ref: values
    - repoURL: https://github.com/TrueBad0ur/local-raspberry-kube-cluster.git
      targetRevision: main
      path: configs/loki
      directory:
        include: "datasource-configmap.yml"
  destination:
    server: https://kubernetes.default.svc
    namespace: loki
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
