# Prerequisite (one-time, not managed here, needs to run on every node):
#   apt install -y open-iscsi nfs-common
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argo-cd
spec:
  project: default
  sources:
    - repoURL: https://charts.longhorn.io
      chart: longhorn
      targetRevision: 1.12.1
      helm:
        valueFiles:
          - $values/configs/longhorn/values.yml
    - repoURL: https://github.com/TrueBad0ur/local-raspberry-kube-cluster.git
      targetRevision: main
      ref: values
    - repoURL: https://github.com/TrueBad0ur/local-raspberry-kube-cluster.git
      targetRevision: main
      path: configs/longhorn
      directory:
        include: "storageclass-rwx.yml"
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
